version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: ${PROJECT_NAME}-mysql
    environment:
      MYSQL_DATABASE:  ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  symfony:
    build: ./docker/image/symfony
    container_name: ${PROJECT_NAME}-symfony
    environment:
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD}@mysql:3306/symfony
      - REDIS_URL=redis://redis
    volumes:
      - ${SOURCE_DIR}:/app
    depends_on:
      - mysql
    networks:
      - backend
  nginx:
    build: ./docker/image/nginx
    container_name: ${PROJECT_NAME}-nginx
    volumes:
      - ${SOURCE_DIR}:/app
    ports:
      - 8080:80
    networks:
      - default
      - backend
    depends_on:
      - symfony
  redis:
    image: redis:alpine
    container_name: ${PROJECT_NAME}-redis
    ports:
        - "6379:6379"
    networks:
      - backend
      - default
networks:
  backend:
  default: